# Generated by Django 5.2.7 on 2025-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('verdict', models.CharField(choices=[('real', 'Real'), ('fake', 'Fake'), ('uncertain', 'Uncertain')], max_length=10)),
                ('confidence', models.FloatField()),
                ('heatmap_path', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
