# Generated by Django 5.2.7 on 2025-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('political', 'Political'), ('celebrity', 'Celebrity'), ('news', 'News'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('analysis_data', models.JSONField(default=dict)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
